name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  firebase: ^5.0.1

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: '>=0.8.10 <0.11.0'
  build_test: ^0.10.2
  build_web_compilers: '>=0.3.6 <0.5.0'
  test: ^1.0.0
